# Generated by Django 5.2.8 on 2025-11-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter Customer Name', max_length=100)),
                ('dob', models.DateField(help_text='Enter Date of Birth')),
                ('customer_email', models.CharField(help_text='Enter Customer Email')),
                ('customer_address', models.CharField(help_text='Enter Customer Address', max_length=200)),
            ],
        ),
    ]
